### ISSUE TITLE
Issue with /xpboost gui

### ISSUE THREAD

**Issue by EvilParagon** [JustDJplease/ExperienceBooster#5]
Whenever I type /xpboost I get "An internal error occurred while attempting to perform this command" Im on Spigot 1.13.2. Here is the error message:
22.04 01:30:41 [Server] ERROR null
22.04 01:30:41 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'xpboost' in plugin ExperienceBoost v0.7
22.04 01:30:41 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
22.04 01:30:41 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
22.04 01:30:41 [Server] INFO at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:704) ~[spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
22.04 01:30:41 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1620) ~[spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
22.04 01:30:41 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1460) ~[spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
22.04 01:30:41 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
22.04 01:30:41 [Server] INFO at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
22.04 01:30:41 [Server] INFO at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:9) ~[spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
22.04 01:30:41 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
22.04 01:30:41 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
22.04 01:30:41 [Server] INFO at net.minecraft.server.v1_13_R2.SystemUtils.a(SourceFile:199) [spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
22.04 01:30:41 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:896) [spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
22.04 01:30:41 [Server] INFO at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417) [spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
22.04 01:30:41 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831) [spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
22.04 01:30:41 [Server] INFO at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729) [spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]
22.04 01:30:41 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
22.04 01:30:41 [Server] INFO Caused by: java.lang.NoSuchFieldError: BLOCK_ENDERCHEST_OPEN
22.04 01:30:41 [Server] INFO at me.theblockbender.xpboost.inventory.BoosterGUI.open(BoosterGUI.java:146) ~[?:?]
22.04 01:30:41 [Server] INFO at me.theblockbender.xpboost.command.BoosterCommand.onCommand(BoosterCommand.java:32) ~[?:?]
22.04 01:30:41 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.13.2.jar:git-Spigot-f09662d-7c395d4]

**Comment by trentnbauer** [comment]
I am also seeing this error,


>.... [18:11:27 INFO]: X4RDONIAK issued server command: /xpboost
>.... [18:11:27 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'xpboost' in plugin ExperienceBoost v0.7
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.15.2.jar:git-Paper-89]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.15.2.jar:git-Paper-89]
at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:742) ~[patched_1.15.2.jar:git-Paper-89]
at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1820) ~[patched_1.15.2.jar:git-Paper-89]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1628) ~[patched_1.15.2.jar:git-Paper-89]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.15.2.jar:git-Paper-89]
at net.minecraft.server.v1_15_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.15.2.jar:git-Paper-89]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-89]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-89]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-89]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-89]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-89]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1038) ~[patched_1.15.2.jar:git-Paper-89]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1031) ~[patched_1.15.2.jar:git-Paper-89]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-89]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1015) ~[patched_1.15.2.jar:git-Paper-89]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:938) ~[patched_1.15.2.jar:git-Paper-89]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.NoSuchMethodError: org.bukkit.inventory.Inventory.getName()Ljava/lang/String;
at me.theblockbender.xpboost.inventory.BoosterGUI.open(BoosterGUI.java:116) ~[?:?]
at me.theblockbender.xpboost.command.BoosterCommand.onCommand(BoosterCommand.java:32) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.15.2.jar:git-Paper-89]
... 17 more

**Comment by JustDJplease** [comment]
The version of the plugin that was being used (1.12) did not support that version of minecraft (1.13).
